version: '2.1'

services:
  authgrpc:
    image: authgrpc
    build: .
    environment:
      NODE_ENV: development
    ports:
      - 6661:6661
      - 9229:9229
    ## set your startup file here
    command: node --inspect index.js